### ISSUE TITLE
ECDSACoin: TypeError when calling get_owner function

### ISSUE THREAD

**Issue by billygarrison** [justinmoon/digital-cash#13]
I get the following error when I run get_owner(coin):
```
TypeError: unhashable type: 'VerifyingKey'
```

Here's a timestamp of the ECDSACoin video where the code is executed:
https://www.youtube.com/watch?v=hujedHkaxLI&feature=youtu.be&t=2578

Traceback shows it is coming from this statement:
```
database = {
    bob_public_key: "Bob",
    alice_public_key: "Alice",
    bank_public_key: "Bank"
}
```
In the Traceback it has an arrow pointing to the `bank_public_key: "Bank"` line, but if I comment out that line then I get the same error but the arrow points to the `alice_public_key: "Alice"` line. And if I comment out that one it points to bob's line.

If I try to print(public_key) It prints:
```
ecdsa.keys.VerifyingKey object at 0x.........>
```

I'm running Python 3.6.3 and encounter this error with the ECDSACoin workbook noteobook as well as the solution notebook.

I was able to finish the ECDSACoin as it doesn't actually require get_owner.

**Comment by justinmoon** [comment]
Thanks for reporting. Fixed in https://github.com/justinmoon/digital-cash/commit/9f44a85dde64620a49d319388003ce538365fe34#diff-eaf45354a1dc8df9f543a080468a9e42R229

**Comment by jodobear** [comment]
Just going through the bootcamp again and this bug still persists. Not sure how to solve this.

Edit: anyone know how to fix this?
